baseURL = 'https://kenanjasim.com/'
languageCode = 'en-gb'
title = 'Kenan (ÙƒÙ†Ø§Ù†)'
theme = "typo"

[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[taxonomies]
tag = 'tags'

# # Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Kenan Jasim's personal blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Salam! ğŸ‘‹'
homeIntroContent = """
I'm Kenan, a software engineer with a background in electronic engineering. 

* ğŸ§‘â€ğŸ’» I have 5+ years of experience in software development.
* ğŸ“ I have a BEng in Electronic and Information Engineering from King's College London.
* ğŸŒ I was born in the UK with Lebanese and Iraqi descent. I am a Muslim and I am fluent in both English and Arabic.
* ğŸ¥ I have had type 1 diabetes since I was a one year old.
* âœˆï¸ I love travelling, learning about different cultures and trying new foods, I also enjoy cooking, reading, photography and running.

I enjoy learning new things and sharing my knowledge with others. This blog is a collection of my thoughts, experiences and learnings. I hope you find it useful. ğŸ™‚
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/kenanjasim.bsky.social"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/kenanjasim/"

[[params.social]]
name = "github"
url = "https://github.com/kenanjasim/"

[[params.social]]
name = "email"
url = "mailto:kenan@kenanjasim.com"

[[params.social]]
name = "rss"
url = "/index.xml"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "cv"
url = "https://kenanjasim.github.io/cv/cv.pdf"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# # Giscus comments
# [params.giscus]
# enable = false
# repo = "user/repo"
# repoid = "repoId"
# category = "General"
# categoryid = "categoryId"
# mapping = "pathname"
# theme = "preferred_color_scheme"
